# =============================================================================
# RBR — Red Bull Racing colors for Powerlevel10k
# Version: 2.1.0-classic
# =============================================================================
#
# This file is a COLOR OVERRIDE for p10k. It does NOT define which segments
# appear or how they're laid out — that stays up to your own `.p10k.zsh`
# generated by `p10k configure`. We only override foreground colors (and a
# few icon colors) so the RBR palette wins the eye.
#
# Install:
#   1. Run `p10k configure` once to generate ~/.p10k.zsh (your layout).
#   2. Copy this file somewhere (e.g. ~/.config/p10k/rbr.zsh).
#   3. In ~/.zshrc, source BOTH — this file AFTER your .p10k.zsh:
#
#        [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
#        [[ -f ~/.config/p10k/rbr.zsh ]] && source ~/.config/p10k/rbr.zsh
#
#   4. Restart zsh.  No other changes needed.
#
# Known limitation — custom formatter functions:
#   `p10k configure` sometimes generates a custom function (e.g.
#   `my_git_formatter`) in your .p10k.zsh that hardcodes colors as
#   function-local variables (`local clean='%76F'` etc). These are NOT
#   reachable from this overlay — you must edit your .p10k.zsh directly.
#
#   How to check:
#       grep -nE '%[0-9]+F' ~/.p10k.zsh
#
#   Replace each `%<N>F` with the RBR `%F{#rrggbb}` form. Mapping:
#       %76F  (green)  -> %F{#e84a55}  kerb_red (or %F{#9cc080} track_green)
#       %178F (yellow) -> %F{#ffd84d}  rb_yellow
#       %39F  (blue)   -> %F{#f5c842}  rb_warm
#       %196F (red)    -> %F{#f56570}  kerb_bright
#       %244F (grey)   -> %F{#6a7495}  subtext0
#       %240F (grey)   -> %F{#4a5580}  overlay1
#       %70F  (green)  -> %F{#9cc080}  track_green
#       %215F (orange) -> %F{#e8b498}  crowd_orange
#
# Requires: powerlevel10k v1.20+ and a truecolor terminal.
# p10k accepts hex colors natively and downgrades to 256-color when needed.
# =============================================================================

# ---- Palette shorthand ------------------------------------------------------
# (locals so they don't leak into the shell environment)
local rbr_kerb_red='#e84a55'
local rbr_kerb_bright='#f56570'
local rbr_rb_yellow='#ffd84d'
local rbr_rb_warm='#f5c842'
local rbr_oracle_blue='#82a0d8'
local rbr_sky_blue='#a4bde8'
local rbr_paddock_green='#b8d49e'
local rbr_track_green='#9cc080'
local rbr_warm_pink='#d49880'
local rbr_crowd_orange='#e8b498'
local rbr_teal='#95c0c8'
local rbr_pit_light='#b0d4dc'
local rbr_text='#c8d0e8'
local rbr_subtext1='#8590ae'
local rbr_subtext0='#6a7495'
local rbr_overlay1='#4a5580'

# ---- Prompt character -------------------------------------------------------
# The blinking/solid prompt char. Yellow when command succeeded,
# bright red when the previous command failed.
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$rbr_rb_yellow
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$rbr_kerb_bright

# ---- Multiline ruler / gap --------------------------------------------------
typeset -g POWERLEVEL9K_RULER_FOREGROUND=$rbr_overlay1
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=$rbr_overlay1

# ---- Directory --------------------------------------------------------------
typeset -g POWERLEVEL9K_DIR_FOREGROUND=$rbr_sky_blue
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$rbr_subtext1
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$rbr_text
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

# ---- Git / VCS --------------------------------------------------------------
# Clean branch  → kerb_red (the one active branch)
# Modified      → rb_yellow (attention — unpushed work)
# Untracked     → rb_warm (softer warning)
# Conflicted    → kerb_bright (fix me now)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$rbr_kerb_red
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$rbr_rb_yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$rbr_rb_warm
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$rbr_subtext1

# VCS segment icon (separate from text foreground — lives on VISUAL_IDENTIFIER_COLOR).
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=$rbr_kerb_red
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=$rbr_subtext0

# ---- Status (exit code) -----------------------------------------------------
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$rbr_paddock_green
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=$rbr_paddock_green
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$rbr_kerb_bright

# ---- Command execution time -------------------------------------------------
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$rbr_subtext1

# ---- Background jobs --------------------------------------------------------
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$rbr_crowd_orange

# ---- Context (user@host) ----------------------------------------------------
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=$rbr_subtext1
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=$rbr_rb_yellow
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=$rbr_kerb_bright

# ---- Kubernetes context -----------------------------------------------------
# Prod contexts render in kerb_bright so "you're on prod" reads at a glance.
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=$rbr_oracle_blue
typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_KUBECONTEXT_TEST_FOREGROUND=$rbr_rb_yellow
typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_FOREGROUND=$rbr_paddock_green

# ---- Python envs (virtualenv, pyenv, anaconda) ------------------------------
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$rbr_crowd_orange
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=$rbr_crowd_orange
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=$rbr_crowd_orange

# ---- Cloud providers --------------------------------------------------------
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=$rbr_crowd_orange
typeset -g POWERLEVEL9K_AWS_EB_ENV_DEFAULT_FOREGROUND=$rbr_crowd_orange
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=$rbr_crowd_orange
typeset -g POWERLEVEL9K_AZURE_FOREGROUND=$rbr_crowd_orange

# ---- Language versions ------------------------------------------------------
typeset -g POWERLEVEL9K_GOENV_FOREGROUND=$rbr_teal
typeset -g POWERLEVEL9K_NODENV_FOREGROUND=$rbr_paddock_green
typeset -g POWERLEVEL9K_NVM_FOREGROUND=$rbr_paddock_green
typeset -g POWERLEVEL9K_RBENV_FOREGROUND=$rbr_kerb_red
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=$rbr_crowd_orange

# ---- Docker / Kubernetes ----------------------------------------------------
typeset -g POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND=$rbr_oracle_blue

# ---- Battery ----------------------------------------------------------------
typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=$rbr_kerb_bright
typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=$rbr_rb_yellow
typeset -g POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=$rbr_paddock_green
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=$rbr_subtext1
